spring:
  application:
    name: ressourceRelationnelle

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        type:
          preferred_uuid_jdbc_type: CHAR

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

security:
  jwt:
    access-token-ttl-minutes: 15
    refresh-token-ttl-days: 7