spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://localhost}

security:
  refresh-cookie:
    secure: true
    same-site: Strict
    path: /api/auth
  jwt:
    secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8080}