CREATE USER IF NOT EXISTS 'user1'@'%' IDENTIFIED BY 'pass1';
CREATE USER IF NOT EXISTS 'user2'@'%' IDENTIFIED BY 'pass2';
CREATE USER IF NOT EXISTS 'user3'@'%' IDENTIFIED BY 'pass3';

GRANT ALL PRIVILEGES ON rrDb.* TO 'user1'@'%';
GRANT ALL PRIVILEGES ON rrDb.* TO 'user2'@'%';
GRANT ALL PRIVILEGES ON rrDb.* TO 'user3'@'%';

FLUSH PRIVILEGES;
